[package]
name = "cdk-ffi-dart"
edition = "2021"
rust-version = "1.85.0"
license = "MIT"
homepage = "https://github.com/cashubtc/cdk"
repository = "https://github.com/cashubtc/cdk.git"
version = "0.17.1"
readme = "README.md"

[lib]
crate-type = ["staticlib", "cdylib"]
name = "cdk_ffi_dart"

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"

[dependencies]
alloc-stdlib = "=0.2.2"
arrayvec = "=0.7.6"
bitflags = "=2.11.1"
brotli = "=8.0.3"
brotli-decompressor = "=5.0.1"
bytes = "=1.11.1"
cc = "=1.2.63"
chrono = "=0.4.44"
getrandom = "=0.4.2"
http = "=1.4.1"
js-sys = "=0.3.99"
lightning = "=0.2.2"
lightning-invoice = "=0.34.0"
lightning-types = "=0.3.1"
log = "=0.4.30"
memchr = "=2.8.1"
possiblyrandom = "=0.2.0"
quinn = "=0.11.9"
quinn-proto = "=0.11.14"
quote = "=1.0.45"
regex = "=1.12.3"
regex-syntax = "=0.8.10"
rustls = "=0.23.40"
serde_with = "=3.20.0"
serde_with_macros = "=3.20.0"
smallvec = "=1.15.1"
smawk = "=0.3.2"
syn = "=2.0.117"
time = "=0.3.47"
time-core = "=0.1.8"
time-macros = "=0.2.27"
uuid = "=1.23.2"
wasip2 = "=1.0.3+wasi-0.2.9"
wasm-bindgen = "=0.2.122"
wasm-bindgen-futures = "=0.4.72"
wasm-bindgen-macro = "=0.2.122"
wasm-bindgen-macro-support = "=0.2.122"
wasm-bindgen-shared = "=0.2.122"
web-sys = "=0.3.99"
webpki-roots = "=1.0.7"
yoke = "=0.8.2"
zerocopy = "=0.8.50"
zerocopy-derive = "=0.8.50"
zeroize = "=1.8.2"
cdk-ffi = { version = "=0.17.1", default-features = false, features = ["npubcash", "bip353"] }
uniffi = { version = "0.30", features = ["cli"] }
uniffi-dart = { git = "https://github.com/Uniffi-Dart/uniffi-dart", tag = "v0.1.0+v0.30.0"  }
camino = "1.2"

[build-dependencies]
uniffi = { version = "0.30", features = ["build"] }
uniffi-dart = { git = "https://github.com/Uniffi-Dart/uniffi-dart", features = ["build"], tag = "v0.1.0+v0.30.0"  }

[lints]


[workspace]

[profile.release]
lto = true
strip = true
codegen-units = 1
